### PR TITLE
v2.4.0

### LINKED ISSUE #66: v2.4.0
v2.4.0 released: https://github.com/streamlink/streamlink/releases/tag/2.4.0

### PR DESCRIPTION
**Pull request by Conjuro**
- [x] v2.4.0 of Streamlink
- [x] Resolves #66
- [x] Updated checksum
- [x] Updated link to changelog
- [x] Add OS version check to install script
- [x] Test before pushing to Chocolatey
- [ ] Pending package approval: https://chocolatey.org/packages/streamlink/2.4.0

### CODE REVIEW

**Comment by Conjuro** [comment]
https://github.com/streamlink/streamlink-chocolatey/issues/66#issuecomment-914231543

**Comment by Conjuro** [comment]
PR incomplete. Need to add a OS version check, and error out versions below W10.

https://docs.chocolatey.org/en-us/create/create-packages#install-only-on-some-versions-of-windows

**Comment by Conjuro** [comment]
Added a check for Windows version that throws an error if below version 10. Tested it on both W7 and W10 (VM); Failed on W7 without affecting current installation, successfully upgraded on W10.

Didn't use 'Write-ChocolateyFailure' as Chocolatey documentation indicates it's [deprecated](https://docs.chocolatey.org/en-us/create/functions/write-chocolateyfailure).

@scowalt Does this look good to you?

**Comment by scowalt** [comment]
LGTM, thanks for testing that case (and in general for maintaining this package 🙂)

**Comment by Conjuro** [comment]
Chocolatey verification servers are running on Windows Server 2012 R2, which is causing the verification testing to fail.

@bastimeyer If I understand it correctly, it's only W7 that is incompatible with the included Python version? All newer Windows version would work, we just don't officially support anything below W10?

<table>
<tr>
	<td>
		Operating system
	<td>
		Version number
<tr>
	<td>
		Windows 10
	<td>
		10.0
<tr>
	<td>
		Windows Server 2019
	<td>
		10.0
<tr>
	<td>
		Windows Server 2016
	<td>
		10.0
<tr>
	<td>
		Windows 8.1
	<td>
		6.3
<tr>
	<td>
		Windows Server 2012 R2
	<td>
		6.3
<tr>
	<td>
		Windows 8
	<td>
		6.2
<tr>
	<td>
		Windows Server 2012
	<td>
		6.2
<tr>
	<td>
		Windows 7
	<td>
		6.1
<tr>
	<td>
		Windows Server 2008 R2
	<td>
		6.1
</table>

A possible solution would be to lower the requirement check to version 6.3 (or 6.2) for now, and hope they upgrade their servers by the time the newer versions become incompatible as well.

Alternatively I'll have to reach out to Chocolatey support for other options. There might be an environment variable we could check against to exclude the verification servers from the version check; Or, they might have some other solutions.

**Comment by bastimeyer** [comment]
> If I understand it correctly, it's only W7 that is incompatible with the included Python version? All newer Windows version would work, we just don't officially support anything below W10?

https://github.com/streamlink/streamlink/pull/3918
https://www.python.org/downloads/release/python-390/

W8 should still be compatible, but as I said in streamlink/streamlink#3918 it makes more sense setting the minimum requirement in the docs to W10 because W8 and W8.1 have already seen their EOL in 2018 and they don't have any marketshare anymore.
https://endoflife.date/windows

----

Btw, you're not limited by Streamlink's Windows installer here in the chocolatey package. py8 is still supported and will stay supported until it reaches its EOL in 2024:
https://endoflife.date/python

The reason why py38 was dropped from the upstream installer is that we don't want to publish an installer with an outdated embedded python install which can't be upgraded anymore due to py38 having entered its source-only security release cycle in June already. Shipping an outdated and unpatched version would come at the cost of all users of non-outdated systems where official up-to-date pre-built python releases are still available. However, if one wants to maintain a repo which builds py38 for Windows from source, same like we're now doing with FFmpeg, then that could be used by the installer without any problems.

As an independent package that needs to include an embedded python install, you can ship any python version that is technically still supported by the project, [which is `>=3.6, <4`](https://github.com/streamlink/streamlink/blob/2.4.0/setup.py#L107), but it's up to you to decide what makes the most sense in terms of effort, stability and security. From the looks of it, the python3 chocolatey package limits 3.8 to 3.8.10, which is the last official py38 pre-built release.

**Comment by scowalt** [comment]
My opinion is either to set the minimum version to 6.3 _or_ to see if there is an environment variable to read in the production environment.

**Comment by IeUDE** [comment]
Any development on this @Conjuro @scowalt ... ?
Thank you very much for all the effort!

**Comment by scowalt** [comment]
Hopefully this will be resolved with https://github.com/streamlink/streamlink/pull/4356

We can get an exemption for `streamlink` so we don't have to worry about compatibility with old Windows versions

**Comment by scowalt** [comment]
I folded this change into the repository, then automated the package publishing process.

**Pull request closed without merging**
